site_name: Textual文档

repo_url: https://github.com/i-am-wyk/textual-translate
repo_name: i-am-wyk/textual-translate

nav:
    - 关于此文档: 'about.md'
    - 介绍:
      - "index.md"
      - "getting_started.md"
      - "help.md"


theme:
  name: material
  icon:
    repo: simple/github
    edit: material/pencil

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
  language: zh

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - admonition
  - def_list
  - meta

  - toc:
      permalink: true
      baselevel: 1
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: textual
          class: textual
          format: !!python/name:textual._doc.format_svg
        - name: rich
          class: rich
          format: !!python/name:textual._doc.rich
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - markdown.extensions.attr_list

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      
extra_css:
  - stylesheets/custom.css