site_name: Textual文档

repo_url: https://github.com/i-am-wyk/textual-translate
repo_name: i-am-wyk/textual-translate

theme:
  name: material
  icon:
    repo: simple/github
    edit: material/pencil

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
  language: zh

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences


  - toc:
      permalink: true
      baselevel: 1
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: textual
          class: textual
          format: !!python/name:textual._doc.format_svg
        - name: rich
          class: rich
          format: !!python/name:textual._doc.rich
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - markdown.extensions.attr_list

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      
nav:
    - 主页: 'index.md'
    - 教程: 'index.md'
